stages:
  - build
  - deploy

variables:
  # NODE_ENV: production  # 주석 처리 또는 제거

build:
  stage: build
  tags:
    - windows
  script:
    - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash"
    - ". ~/.nvm/nvm.sh && nvm install 18 && nvm use 18"
    - "export PATH=$CI_PROJECT_DIR/node_modules/.bin:$PATH"
    - "rm -rf node_modules"
    - "npm install --include=dev"
    - "ls $CI_PROJECT_DIR/node_modules/.bin" # node_modules/.bin 디렉터리 확인
    - "vite build"
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  tags:
    - windows
  script:
    - "scp -O -P 58176 -r dist/ root@192.168.0.101:/esl/TeWeb"
    - "ssh -p 58176 root@192.168.0.101 \"cd /esl/TeWeb && nohup node server.js > server.log 2>&1 &\""