stages:
  - build
  - deploy

variables:
  NODE_ENV: production

build:
  stage: build
  tags:
    - windows
  script:
    - "C:/Program Files/Git/bin/bash.exe -c 'cd $CI_PROJECT_DIR && npm run build'"
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  tags:
    - windows
  script:
    - "C:/Program Files/Git/bin/bash.exe -c 'cd $CI_PROJECT_DIR && scp -O -P 58176 -r dist/ root@192.168.0.101:/esl/TeWeb'"
    - "C:/Program Files/Git/bin/bash.exe -c 'cd $CI_PROJECT_DIR && ssh -p 58176 root@192.168.0.101 \"cd /esl/TeWeb && nohup node server.js > server.log 2>&1 &\"'"