stages:
  - test
  - build
  - deploy

variables:
  NODE_ENV: production

test-bash:
  stage: test
  tags: 
    - windows
  script:
    - echo "Running on Bash"
    - bash --version

build:
  stage: build
  tags: 
    - windows
  script:
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  tags: 
    - windows
  script:
    # 빌드 파일 및 server.js를 임베디드 리눅스로 전송
    - scp -O -P 58176 -r dist/ root@192.168.0.101:/esl/TeWeb
    # 서버 실행
    - ssh -p 58176 root@192.168.0.101 "cd /esl/TeWeb && nohup node server.js > server.log 2>&1 &"