stages:
  - build
  - deploy
build:
  stage: build
  tags:
    - windows
  script:
    - "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash"
    - ". ~/.nvm/nvm.sh && nvm install 18 && nvm use 18"
    - "export PATH=$CI_PROJECT_DIR/node_modules/.bin:$PATH"
    - "rm -rf node_modules"
    - "npm install --include=dev"
    - "ls $CI_PROJECT_DIR/node_modules/.bin" # node_modules/.bin 디렉터리 확인
    - "vite build"
    # setup_server.sh와 libatomic.so.1.2.0 파일을 /dist 폴더에 복사
    - "cp setup_server.sh dist/"
    - "cp libatomic.so.1.2.0 dist/"
  artifacts:
    paths:
      - dist/
deploy:
  stage: deploy
  tags:
    - windows
  before_script:
    - "mkdir -p ~/.ssh"
    - "echo \"$SSH_PRIVATE_KEY\" > ~/.ssh/id_rsa" # SSH 비공개 키 설정
    - "chmod 600 ~/.ssh/id_rsa"
    - "ssh-keyscan -p 58176 192.168.0.101 >> ~/.ssh/known_hosts" # 서버의 호스트 키 추가
        # GitLab Runner에서 CRLF 문제 방지
    - "find . -type f -exec sed -i 's/\r$//' {} +"
  script:
    # 1. /dist 폴더의 모든 파일을 서버로 복사
    - "scp -O -P 58176 -r dist/ root@192.168.0.101:/esl/TeWeb"
    # 2. 서버에서 줄바꿈 형식 변환
    #- "ssh -p 58176 root@192.168.0.101 \"sed -i 's/\\r\$//' /esl/TeWeb/dist/setup_server.sh && echo 'sed command executed'\""
    # 3. setup_server.sh 실행 권한 추가
    - "ssh -p 58176 root@192.168.0.101 \"chmod +x /esl/TeWeb/dist/setup_server.sh\""
    # 4. 서버에서 setup_server.sh 실행
    - "ssh -p 58176 root@192.168.0.101 \"bash /esl/TeWeb/dist/setup_server.sh\""