 export const createLine = (selectedTag, currentObjects) => {
    const startX = (selectedTag.Width - 100) / 2;
    const startY = selectedTag.Height / 2;
    const length = 100;
    return {
      Type: "Line",
      ZOrder: currentObjects.length,
      PenWidth: 1,
      PenColor: "Black",
      FillColor: "White",
      IsFilled: false,
      PosX: startX,
      PosY: startY,
      PosX1: startX + length,
      PosY1: startY,
      Height: 0,
      Width: length,
      Rotation: 0,
      Font: "Arial, 12pt",
      Text: null,
      Align: 0,
      VAlign: 1,
      DataName: null,
      ShowBarcodeLabel: false,
      ShowBoarder: true,
      ArcsWidth: 20,
      Margin: 0,
      Arrow: 0,
      ArrowSize: 5,
      BorderShape: 0,
      Newline: "",
      Subject: "",
      CodeType: 0,
      Reference: 0,
      SizeMode: 2,
      ProductID: 0,
      MultiFacingMode: false,
      SingleLine: true,
      LineHeight: 16,
      ImageBase64: null
    };
  };

export const createRect = (selectedTag, currentObjects) => ({
    Type: "Rect",
    ZOrder: currentObjects.length,
    PenWidth: 1,
    PenColor: "Black",
    FillColor: "White",
    IsFilled: false,
    PosX: (selectedTag.Width - 100) / 2,
    PosY: (selectedTag.Height - 100) / 2,
    PosX1: 0,
    PosY1: 0,
    Height: 100,
    Width: 100,
    Rotation: 0,
    Font: "Arial, 12pt",
    Text: null,
    Align: 0,
    VAlign: 1,
    DataName: null,
    ShowBarcodeLabel: false,
    ShowBoarder: true,
    ArcsWidth: 20,
    Margin: 0,
    Arrow: 0,
    ArrowSize: 5,
    BorderShape: 0,
    Newline: "",
    Subject: "",
    CodeType: 0,
    Reference: 0,
    SizeMode: 2,
    ProductID: 0,
    MultiFacingMode: false,
    SingleLine: true,
    LineHeight: 16,
    ImageBase64: null
  });

export const createRoundRect = (selectedTag, currentObjects) => ({
  Type: "roundrect",
  ZOrder: currentObjects.length,
  PenWidth: 1,
  PenColor: "Black",
  FillColor: "White",
  IsFilled: false,
  PosX: (selectedTag.Width - 100) / 2,
  PosY: (selectedTag.Height - 100) / 2,
  PosX1: 0,
  PosY1: 0,
  Height: 100,
  Width: 100,
  Rotation: 0,
  Font: "Arial, 12pt",
  Text: null,
  Align: 0,
  VAlign: 1,
  DataName: null,
  ShowBarcodeLabel: false,
  ShowBoarder: true,
  ArcsWidth: 16,      // 둥근 정도(픽셀, 필요시 조정)
  Margin: 0,
  Arrow: 0,
  ArrowSize: 5,
  BorderShape: 1,     // ★ 둥근 사각형 표시
  Newline: "",
  Subject: "",
  CodeType: 0,
  Reference: 0,
  SizeMode: 2,
  ProductID: 0,
  MultiFacingMode: false,
  SingleLine: true,
  LineHeight: 16,
  ImageBase64: null
});

export const createEllipse = (selectedTag, currentObjects) => ({
  Type: "ellipse", // 소문자 권장
  ZOrder: currentObjects.length,
  PenWidth: 1,
  PenColor: "Black",
  FillColor: "White",
  IsFilled: false,
  PosX: (selectedTag.Width - 100) / 2,
  PosY: (selectedTag.Height - 60) / 2,
  PosX1: 0,
  PosY1: 0,
  Height: 100,
  Width: 100,
  Rotation: 0,
  Font: "Arial, 12pt",
  Text: null,
  Align: 0,
  VAlign: 1,
  DataName: null,
  ShowBarcodeLabel: false,
  ShowBoarder: true,
  ArcsWidth: 20,
  Margin: 0,
  Arrow: 0,
  ArrowSize: 5,
  BorderShape: 0,
  Newline: "",
  Subject: "",
  CodeType: 0,
  Reference: 0,
  SizeMode: 2,
  ProductID: 0,
  MultiFacingMode: false,
  SingleLine: true,
  LineHeight: 16,
  ImageBase64: null
});

export const createText = (selectedTag, currentObjects) => {
  const centerX = (selectedTag.Width - 200) / 2;
  const centerY = (selectedTag.Height - 30) / 2;
  return {
    Type: "text",
    ZOrder: currentObjects.length,
    PenWidth: 1,
    PenColor: "Black",
    FillColor: "White",
    IsFilled: false,
    PosX: centerX,
    PosY: centerY,
    PosX1: 0,
    PosY1: 0,
    Height: 30,
    Width: 200,
    Rotation: 0,
    Font: "Arial, 12pt",
    Text: "Double click to edit",
    Align: 0,
    VAlign: 1,
    DataName: null,
    ShowBarcodeLabel: false,
    ShowBoarder: false,
    ArcsWidth: 20,
    Margin: 0,
    Arrow: 0,
    ArrowSize: 5,
    BorderShape: 0,
    Newline: "",
    Subject: "",
    CodeType: 0,
    Reference: 0,
    SizeMode: 2,
    ProductID: 0,
    MultiFacingMode: false,
    SingleLine: true,
    LineHeight: 16,
    ImageBase64: null,
  };
};

export const createArrow = (selectedTag, currentObjects) => ({
  Type: "arrow", // 소문자 권장
  ZOrder: currentObjects.length,
  PenWidth: 2,
  PenColor: "Black",
  FillColor: "White",
  IsFilled: false,
  PosX: (selectedTag.Width - 100) / 2,
  PosY: selectedTag.Height / 2,
  PosX1: (selectedTag.Width + 100) / 2,
  PosY1: selectedTag.Height / 2,
  Height: 0,
  Width: 100,
  Rotation: 0,
  Font: "Arial, 12pt",
  Text: null,
  Align: 0,
  VAlign: 1,
  DataName: null,
  ShowBarcodeLabel: false,
  ShowBoarder: true,
  ArcsWidth: 20,
  Margin: 0,
  Arrow: 1,         // ★ 화살표 표시
  ArrowSize: 12,    // 화살촉 크기(필요시 조정)
  BorderShape: 0,
  Newline: "",
  Subject: "",
  CodeType: 0,
  Reference: 0,
  SizeMode: 2,
  ProductID: 0,
  MultiFacingMode: false,
  SingleLine: true,
  LineHeight: 16,
  ImageBase64: null
});
